import type { NextPage } from 'next';
import { useState, useEffect } from 'react';
import Head from 'next/head';
import Download from '../components/Download';
import Features from '../components/Features';
import Gallery from '../components/Gallery';
import NavBar from '../components/NavBar';
import SplashScreen from '../components/SplashScreen';
import About from '../components/About';
import Footer from '../components/Footer';
import ScrollButton from '../components/ScrollButton';
import debounce from 'lodash.debounce';
import { useRouter } from 'next/router';

const links = [
  {
    name: 'features',
    path: '#features',
    icon: require('../public/images/shimmer.png'),
    alt: 'features icon',
  },
  {
    name: 'gallery',
    path: '#gallery',
    icon: require('../public/images/gallery.png'),
    alt: 'gallery icon',
  },
  {
    name: 'download',
    path: '#download',
    icon: require('../public/images/download.png'),
    alt: 'download icon',
  },
  {
    name: 'about',
    path: '#about-the-devs',
    icon: require('../public/images/clover.png'),
    alt: 'clover icon',
  },
];

const Home: NextPage = () => {
  const [scrollPosition, setScrollPosition] = useState(0);
  const [windowHeight, setWindowHeight] = useState(0);
  const router = useRouter()

  function scrollToTop() {
    router.push('/')
  }

  useEffect(() => {
    const height = window.screen.height;
    setWindowHeight(height);

    const handleScroll = debounce(() => {
      const currentPosition =
        (window.scrollY || document.documentElement.scrollTop) -
        (document.documentElement.clientTop || 0);
      setScrollPosition(currentPosition);
    }, 100);

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <div>
      <Head>
        <title>Flip App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar links={links} />
      <ScrollButton
        onClick={scrollToTop}
        visible={scrollPosition > windowHeight}
      />
      <main>
        <SplashScreen />
        <Features />
        <Gallery />
        <Download />
        <About />
        <Footer />
      </main>
    </div>
  );
};

export default Home;
